version: '3.5'
services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    volumes:
      - ./server.json:/etc/v2ray/config.json
    ports:
      - "2019:2019"
    command: ["v2ray","-config=/etc/v2ray/config.json"]
